dashboard
oberruti/frro-soporte-2020-01 pull request #19
Opened 2020-08-12 20:28 UTC by giovamarr

bootstrap: dashboard, footer, header y navbar

2020-08-12 22:56 UTC, oberruti commented
@giovamarr As a first view, don’t commit the sql lite file, please delete from here! Thanks

2020-08-17 00:04 UTC, oberruti commented
Can you post a GIF or screenshots always that you change something in the frontend? This is really helpful for the reviewer! Thanks.

2020-08-17 00:08 UTC, oberruti requested changes
Good changes, I will wait for a gif or images to see what you did here. Also, did you add the `.sql` file in the `.gitignore`? Thanks.

2020-08-17 00:08 UTC, oberruti commented on practico_08/autogestion_alumnos/__init__.py
> +    bootstrap = Bootstrap(app)
Is it more important that the `init` ? I think that this should be the last in the list of these initializations. Can you change this?

2020-08-17 00:08 UTC, oberruti commented on practico_08/autogestion_alumnos/templates/footer.html
> +            <div class="text-muted">Copyright &copy; Your Website 2020</div>
I think that you forget to change something here, please review it.

2020-08-26 20:04 UTC, giovamarr commented
![soporte_dashboard](https://user-images.githubusercontent.com/51095800/91350121-a23d0f80-e7bc-11ea-9e9e-3d5162f9271a.png)
Dashboard ready

2020-08-27 13:36 UTC, oberruti requested changes
Some changes needed. Really really good job Giova!

2020-08-27 13:36 UTC, oberruti commented on practico_08/autogestion_alumnos/templates/base.html
> +    {% include 'footer.html' %}
I think this is wrong, the include shouldn't be between block and endblock? if not we should delete these two first lines.

2020-08-27 13:36 UTC, oberruti commented on practico_08/autogestion_alumnos/templates/dashboard.html
> +
please delete this empty line

2020-08-27 13:36 UTC, oberruti commented on practico_08/autogestion_alumnos/templates/dashboard.html
> +<!DOCTYPE html>
I don't know where to write this so I'm writing it here, PLEASE PLEASE, WRITE RIGHT NAMES, images/1.png is not a good name, please, change all those image names, to something like logo-calendar or similar. Thanks!

2020-08-27 21:50 UTC, giovamarr commented
![soporte_tasks](https://user-images.githubusercontent.com/51095800/91498448-26af9100-e896-11ea-9154-3a351a758eb4.png)
Fix and template tasks

2020-08-27 21:50 UTC, merged