Name changes
oberruti/frro-soporte-2020-01 pull request #26
Opened 2020-09-10 13:58 UTC by giovamarr

2020-09-10 14:03 UTC, oberruti requested changes

2020-09-10 14:03 UTC, oberruti commented on practico_08/autogestion_alumnos/react-frontend/src/components/test/index.tsx
>                  <i></i>
I think you forget to delete this?

2020-09-12 04:34 UTC, oberruti requested changes
.

2020-09-13 00:09 UTC, giovamarr commented on practico_08/autogestion_alumnos/react-frontend/src/components/test/index.tsx
>                  <i></i>
Yes, ready

2020-09-13 17:56 UTC, merged