Practico 03
oberruti/frro-soporte-2020-01 pull request #4
Opened 2020-04-11 21:37 UTC by giovamarr

2020-04-11 22:15 UTC, oberruti commented on practico_03/ejercicio_03.py
> +        return False
Suponiendo el codigo escrito aca se interpreta como: 
```
If (valor de cursor.rowcount es true):
 return True
else (cuando el valor es falso): 
 return False 
```
Entonces esto se puede modificar a simplemente
 `return cursor.rowcount`
Pero en realidad la pregunta que nos queremos hacer aca es si cursos.rowcount es distinto de 0, entonces retornamos True, y sino False.

2020-04-11 22:23 UTC, oberruti commented on practico_03/ejercicio_03.py
> +        return False
Por otro lado no es necesario el uso del else en ese codigo. Simplemente if algo return algo, abajo return otra cosa

2020-04-11 22:23 UTC, oberruti commented on practico_03/ejercicio_04.py
> +        return False
no es necesario el else.

2020-04-11 22:27 UTC, oberruti commented on practico_03/ejercicio_05.py
>      return False
Esto no esta bien, el ultimo `return no es utilizado nunca` 
Esto deberia ser
```
        return True
return False
```

2020-04-11 22:30 UTC, oberruti commented on practico_03/ejercicio_06.py
> +
Hay dos borrar_tabla_peso. Esto esta mal. Deberia existir un solo metodo con el mismo nombre, y el correcto parece ser el segundo.

2020-04-11 22:38 UTC, oberruti commented on practico_03/ejercicio_07.py
> +
no es necesario el else

2020-04-11 22:38 UTC, oberruti commented on practico_03/ejercicio_07.py
> +
esta mal la identacion

2020-04-11 22:39 UTC, oberruti commented on practico_03/ejercicio_07.py
> +        cSQL = "SELECT FECHA FROM PersonaPeso WHERE IdPersona = %s"
no es Select Fecha ?

2020-04-11 22:44 UTC, oberruti commented
En general parece todo bien, hice algunas correcciones de algunos errores y algunos improvement. Le pongo el Review Request al profe. Buen laburo @giovamarr  !

2020-04-13 06:51 UTC, ELC commented on practico_03/ejercicio_01.py
> +
Falta `commit` and `close`

2020-04-13 06:52 UTC, ELC commented on practico_03/ejercicio_01.py
Falta `commit` and `close`

2020-04-13 06:54 UTC, ELC commented on practico_03/ejercicio_02.py
Falta `close`

2020-04-13 06:54 UTC, ELC commented on practico_03/ejercicio_02.py
> +pruebas()
Si se elimina el bloque IF se ejecutarán las pruebas cada vez que se importe el archivo, eso es lo que quieren?

2020-04-13 06:55 UTC, ELC commented on practico_03/ejercicio_03.py
Falta `close`

2020-04-13 07:01 UTC, ELC requested changes
La soluciones están bien planteadas. Son necesarias algunas correcciones:
- Agregar los `commit` y los `close` en los ejercicios que no lo tengan
- Justificar por qué cambiaron el bloque IF __name__ (Como comentario en la PR)
- Explicar brevemente en un comentario en la PR por qué usaron MySQL en lugar de la base de datos que viene por defecto (SQLite3)
- Justificar por qué cambiaron los test de `datetime` a `date` en los tests (como comentario en la PR)

2020-04-13 07:02 UTC, ELC commented
Excelente trabajo en equipo y el uso de la PR para poder marcar errores!

2020-04-13 18:27 UTC, oberruti commented
@ELC :
1- @giovamarr agregar commits and closes
2- Simplemente para que se ejecute al abrir el archivo
3- @giovamarr podras responder a eso?
4- Porque el enunciado pedia date y no datetime, lo podes ver en el codigo.

2020-04-20 20:25 UTC, ELC commented
@giovamarr @oberruti  Están agregados los ejercicios de Google Drive?

2020-04-20 20:26 UTC, oberruti commented
@ELC no, requieren mas tiempo y son iguales a los otros, muchos estaban copiados. Seguimos la guia de los ejercicios de github. Segun los profes, es suficiente.

2020-06-06 23:50 UTC, merged